### ISSUE TITLE
指摘事項について

### ISSUE THREAD

**Issue by YutamaKotaro** [besutome/slides#2]
拝見させていただきました！

一旦みて思ったことを書かせていただきます。他にも上がったりするかもしれません。
誤字脱字等の発見がありましたら、送っていただいたようにPR送っていきます。

思ったことを指摘させていただいただけなので、無視していただいでも大丈夫です！

## インストールについて

```
react-native init test && cd test
react-native run-ios
```

はインストールとは別段に、プロジェクト作成＆実行といった感じに分けたほうがいいかなと感じました・・・！！

## Tutorial/State

> Props は一度コンポーネントが作成されると変更されませんが、

とあるのですが、

> Propsは親コンポーネントから渡されるものですが、

にするのはどうでしょう？
インスタンス化の後は不変ということに見えると少し思ったのであげさせていただきました！

## ScrollView/ListView

> ScrollView / ListView
> 
> スクロール領域を指定したい場合は、 <ScrollView> もしくは <ListView> で指定する必要があります。
> それぞれの違いは以下です。
> 以下略・・・

とあるんですが、引用ではなくScrollView/ListViewを見出しにしたほうがみやすいかなと思いました。

**Comment by besutome** [comment]
ありがとうございます！
インストールとstateのところは修正します！

ScrollView/ListView
のところはRNのチュートリアルと同じ章立てにしたいので、現状のまま行きます！
